# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('birth_date', models.DateField(max_length=125, null=True)),
                ('address', models.CharField(blank=True, max_length=125, null=True)),
                ('mine_auctions', models.ManyToManyField(to='auctions.Auction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
