# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 14:02
from __future__ import unicode_literals

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, null=True, upload_to=auctions.models.upload_image_path)),
                ('min_price', models.DecimalField(decimal_places=2, default=b'0.00', help_text=b'in Euro.', max_digits=5)),
                ('offer', models.DecimalField(decimal_places=2, help_text=b'in Euro.', max_digits=5, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('category', models.CharField(choices=[(b'comics', b'Comics'), (b'computer parts', b'Computer Parts'), (b'collections', b'Collection'), (b'others', b'Others')], max_length=20)),
                ('deadline', models.DateTimeField()),
                ('high_bidder', models.CharField(default=b'', max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
